// ============================================================
// ÉMOTICÔNES DU VESTIAIRE
// ============================================================
// Le salon ne proposait que 32 émoticônes, choisies à la main. C'était vite
// frustrant : pas de drapeau, pas d'animal, pas de nourriture, rien pour
// chambrer autrement qu'avec 😂.
//
// Cette liste couvre tout ce qu'on envoie réellement dans une conversation,
// rangé par catégories. Chaque entrée porte des mots-clés EN FRANÇAIS, pour
// que la recherche fonctionne dans la langue des joueurs : taper « lens »,
// « biere » ou « rire » doit trouver quelque chose.
//
// Les accents sont volontairement absents des mots-clés : la recherche
// compare des textes déjà mis à plat (voir normaliserRecherche), donc
// « bière » et « biere » tombent sur la même entrée.
// ============================================================

export type EmojiEntry = {
  /** L'émoticône elle-même. */
  c: string;
  /** Mots-clés de recherche, en français, sans accent, séparés par un espace. */
  k: string;
};

export type EmojiCategory = {
  id: string;
  label: string;
  /** Émoticône servant d'onglet — plus lisible qu'un texte sur mobile. */
  icon: string;
  emojis: EmojiEntry[];
};

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: "smileys",
    label: "Émotions",
    icon: "😀",
    emojis: [
      { c: "😀", k: "sourire content joie" },
      { c: "😃", k: "sourire content joie ouvert" },
      { c: "😄", k: "sourire rire joie" },
      { c: "😁", k: "sourire dents ravi" },
      { c: "😆", k: "rire mort de rire" },
      { c: "😅", k: "rire gene sueur ouf" },
      { c: "🤣", k: "mort de rire ptdr roule" },
      { c: "😂", k: "pleure de rire mdr larmes" },
      { c: "🙂", k: "sourire leger" },
      { c: "🙃", k: "envers ironie" },
      { c: "🫠", k: "fond fondre chaud" },
      { c: "😉", k: "clin oeil complice" },
      { c: "😊", k: "content timide sourire" },
      { c: "😇", k: "ange innocent aureole" },
      { c: "🥰", k: "amoureux coeurs adore" },
      { c: "😍", k: "amoureux yeux coeurs" },
      { c: "🤩", k: "etoiles impressionne wow" },
      { c: "😘", k: "bisou baiser" },
      { c: "😗", k: "bisou bouche" },
      { c: "😚", k: "bisou yeux fermes" },
      { c: "😙", k: "bisou sourire" },
      { c: "🥲", k: "sourire larme emu" },
      { c: "😋", k: "miam langue delicieux" },
      { c: "😛", k: "langue tire" },
      { c: "😜", k: "langue clin oeil fou" },
      { c: "🤪", k: "fou dingue delire" },
      { c: "😝", k: "langue yeux fermes" },
      { c: "🤑", k: "argent riche dollars" },
      { c: "🤗", k: "calin bras enlace" },
      { c: "🤭", k: "oups main bouche" },
      { c: "🫢", k: "choque main bouche" },
      { c: "🤫", k: "chut silence" },
      { c: "🤔", k: "reflechit doute pense" },
      { c: "🫡", k: "salut militaire respect" },
      { c: "🤐", k: "bouche cousue secret" },
      { c: "🤨", k: "sourcil doute suspect" },
      { c: "😐", k: "neutre sans expression" },
      { c: "😑", k: "blase inexpressif" },
      { c: "😶", k: "sans bouche muet" },
      { c: "🫥", k: "invisible pointille" },
      { c: "😏", k: "malicieux narquois" },
      { c: "😒", k: "pas content blase" },
      { c: "🙄", k: "yeux au ciel exaspere" },
      { c: "😬", k: "grimace gene malaise" },
      { c: "🤥", k: "menteur pinocchio" },
      { c: "😌", k: "soulage serein" },
      { c: "😔", k: "triste decu pensif" },
      { c: "😪", k: "fatigue dort" },
      { c: "🤤", k: "bave envie" },
      { c: "😴", k: "dort ronfle sommeil" },
      { c: "😷", k: "masque malade" },
      { c: "🤒", k: "malade fievre thermometre" },
      { c: "🤕", k: "blesse bandage" },
      { c: "🤢", k: "degoute nausee" },
      { c: "🤮", k: "vomit degueulasse" },
      { c: "🤧", k: "eternue rhume mouchoir" },
      { c: "🥵", k: "chaud canicule" },
      { c: "🥶", k: "froid gele" },
      { c: "🥴", k: "ivre bourre tete qui tourne" },
      { c: "😵", k: "ko sonne etourdi" },
      { c: "😵‍💫", k: "perdu tete qui tourne" },
      { c: "🤯", k: "explose choque incroyable" },
      { c: "🤠", k: "cowboy chapeau" },
      { c: "🥳", k: "fete cotillons anniversaire" },
      { c: "🥸", k: "deguise moustache" },
      { c: "😎", k: "cool lunettes classe" },
      { c: "🤓", k: "intello lunettes nerd" },
      { c: "🧐", k: "monocle inspecte" },
      { c: "😕", k: "confus perplexe" },
      { c: "🫤", k: "bof mitige" },
      { c: "😟", k: "inquiet soucieux" },
      { c: "🙁", k: "triste leger" },
      { c: "😮", k: "surpris bouche ouverte" },
      { c: "😯", k: "etonne surpris" },
      { c: "😲", k: "stupefait choque" },
      { c: "😳", k: "rouge gene honte" },
      { c: "🥺", k: "supplie sil te plait chien battu" },
      { c: "🥹", k: "retient larmes emu" },
      { c: "😦", k: "decu bouche ouverte" },
      { c: "😧", k: "angoisse" },
      { c: "😨", k: "peur effraye" },
      { c: "😰", k: "angoisse sueur" },
      { c: "😥", k: "decu soulage triste" },
      { c: "😢", k: "pleure triste larme" },
      { c: "😭", k: "pleure fort sanglot" },
      { c: "😱", k: "cri horreur panique" },
      { c: "😖", k: "confus souffre" },
      { c: "😣", k: "persevere souffre" },
      { c: "😞", k: "decu abattu" },
      { c: "😓", k: "sueur decouragement" },
      { c: "😩", k: "epuise las" },
      { c: "😫", k: "fatigue marre" },
      { c: "🥱", k: "baille ennui" },
      { c: "😤", k: "enerve vapeur determine" },
      { c: "😡", k: "colere furieux rouge" },
      { c: "😠", k: "fache colere" },
      { c: "🤬", k: "insulte jure grossier" },
      { c: "😈", k: "diable malicieux" },
      { c: "👿", k: "diable colere" },
      { c: "💀", k: "mort crane" },
      { c: "☠️", k: "tete de mort pirate danger" },
      { c: "💩", k: "caca merde nul" },
      { c: "🤡", k: "clown ridicule" },
      { c: "👹", k: "ogre monstre" },
      { c: "👻", k: "fantome halloween" },
      { c: "👽", k: "alien extraterrestre" },
      { c: "🤖", k: "robot" },
      { c: "🎃", k: "citrouille halloween" },
      { c: "😺", k: "chat content" },
      { c: "😹", k: "chat rire larmes" },
      { c: "😻", k: "chat amoureux" },
      { c: "🙀", k: "chat choque" },
      { c: "😿", k: "chat pleure" },
      { c: "🙈", k: "singe voit rien honte" },
      { c: "🙉", k: "singe entend rien" },
      { c: "🙊", k: "singe dit rien secret" },
    ],
  },
  {
    id: "gestes",
    label: "Gestes",
    icon: "👍",
    emojis: [
      { c: "👍", k: "pouce bien ok daccord" },
      { c: "👎", k: "pouce bas nul pas daccord" },
      { c: "👌", k: "ok parfait nickel" },
      { c: "🤌", k: "italien doigts pincee" },
      { c: "🤏", k: "petit peu pincee" },
      { c: "✌️", k: "victoire peace deux" },
      { c: "🤞", k: "doigts croises chance espere" },
      { c: "🫰", k: "coeur doigts argent" },
      { c: "🤟", k: "je taime rock" },
      { c: "🤘", k: "rock cornes metal" },
      { c: "🤙", k: "appelle moi cool shaka" },
      { c: "👈", k: "doigt gauche" },
      { c: "👉", k: "doigt droite" },
      { c: "👆", k: "doigt haut" },
      { c: "👇", k: "doigt bas" },
      { c: "☝️", k: "index leve attention" },
      { c: "🫵", k: "toi pointe" },
      { c: "✋", k: "main levee stop" },
      { c: "🤚", k: "main dos" },
      { c: "🖐️", k: "main doigts ecartes" },
      { c: "🖖", k: "vulcain spock" },
      { c: "👋", k: "salut coucou bonjour au revoir" },
      { c: "🤝", k: "poignee de main accord deal" },
      { c: "🙏", k: "merci sil te plait priere" },
      { c: "✊", k: "poing force" },
      { c: "👊", k: "poing check boxe" },
      { c: "🤛", k: "poing gauche" },
      { c: "🤜", k: "poing droit" },
      { c: "👏", k: "applaudit bravo" },
      { c: "🙌", k: "bras leves youpi celebration" },
      { c: "🫶", k: "coeur avec les mains amour" },
      { c: "👐", k: "mains ouvertes" },
      { c: "🤲", k: "mains tendues" },
      { c: "🤦", k: "facepalm desespoir main visage" },
      { c: "🤦‍♂️", k: "facepalm homme desespoir" },
      { c: "🤦‍♀️", k: "facepalm femme desespoir" },
      { c: "🤷", k: "sais pas epaules" },
      { c: "🤷‍♂️", k: "sais pas homme" },
      { c: "🤷‍♀️", k: "sais pas femme" },
      { c: "💪", k: "muscle force biceps costaud" },
      { c: "🦾", k: "bras robot force" },
      { c: "🧠", k: "cerveau intelligent reflexion" },
      { c: "👀", k: "yeux regarde matte" },
      { c: "👁️", k: "oeil" },
      { c: "👄", k: "bouche levres" },
      { c: "🫀", k: "coeur organe" },
      { c: "🦵", k: "jambe" },
      { c: "🦶", k: "pied" },
      { c: "👶", k: "bebe" },
      { c: "🧒", k: "enfant" },
      { c: "🧑", k: "personne" },
      { c: "👨", k: "homme" },
      { c: "👩", k: "femme" },
      { c: "🧔", k: "barbe" },
      { c: "👴", k: "vieux papi" },
      { c: "👵", k: "vieille mamie" },
      { c: "👮", k: "policier flic" },
      { c: "🕵️", k: "detective espion enquete" },
      { c: "👷", k: "ouvrier chantier casque" },
      { c: "🤴", k: "prince roi" },
      { c: "👸", k: "princesse reine" },
      { c: "🦸", k: "super heros" },
      { c: "🦹", k: "super vilain mechant" },
      { c: "🧙", k: "magicien sorcier" },
      { c: "🎅", k: "pere noel" },
      { c: "💃", k: "danse femme" },
      { c: "🕺", k: "danse homme" },
      { c: "🕴️", k: "costume classe" },
      { c: "🚶", k: "marche pieton" },
      { c: "🏃", k: "court course rapide" },
      { c: "🧎", k: "genoux supplie" },
      { c: "💆", k: "massage detente" },
      { c: "💇", k: "coiffeur cheveux" },
      { c: "👯", k: "jumelles fete danse" },
      { c: "🗣️", k: "parle gueule crie" },
      { c: "👤", k: "silhouette anonyme" },
      { c: "👥", k: "groupe personnes" },
    ],
  },
  {
    id: "sport",
    label: "Sport",
    icon: "⚽",
    emojis: [
      { c: "⚽", k: "foot football ballon" },
      { c: "🥅", k: "but cage filet" },
      { c: "🏟️", k: "stade enceinte" },
      { c: "🏆", k: "trophee coupe champion victoire" },
      { c: "🥇", k: "or premier medaille 1er" },
      { c: "🥈", k: "argent deuxieme medaille 2e" },
      { c: "🥉", k: "bronze troisieme medaille 3e" },
      { c: "🏅", k: "medaille recompense" },
      { c: "🎖️", k: "medaille militaire honneur" },
      { c: "👟", k: "crampons chaussure basket" },
      { c: "🧤", k: "gants gardien" },
      { c: "🩳", k: "short" },
      { c: "👕", k: "maillot tshirt" },
      { c: "🟨", k: "carton jaune avertissement" },
      { c: "🟥", k: "carton rouge expulsion" },
      { c: "🚩", k: "drapeau touche hors jeu" },
      { c: "⏱️", k: "chrono temps additionnel" },
      { c: "⏲️", k: "minuteur temps" },
      { c: "📣", k: "megaphone supporter encourage" },
      { c: "🎺", k: "trompette tribune" },
      { c: "🥁", k: "tambour tribune ambiance" },
      { c: "🎉", k: "fete cotillons celebration" },
      { c: "🎊", k: "confettis fete" },
      { c: "🔥", k: "feu chaud enflamme excellent" },
      { c: "💥", k: "explosion boom" },
      { c: "⚡", k: "eclair rapide foudre" },
      { c: "💫", k: "etoile vertige" },
      { c: "⭐", k: "etoile favori" },
      { c: "🌟", k: "etoile brillante star" },
      { c: "🏀", k: "basket ballon" },
      { c: "🏈", k: "football americain" },
      { c: "⚾", k: "baseball" },
      { c: "🎾", k: "tennis" },
      { c: "🏐", k: "volley" },
      { c: "🏉", k: "rugby" },
      { c: "🎱", k: "billard huit" },
      { c: "🏓", k: "ping pong tennis de table" },
      { c: "🏸", k: "badminton" },
      { c: "🥊", k: "boxe gant combat" },
      { c: "🥋", k: "judo karate arts martiaux" },
      { c: "⛳", k: "golf trou" },
      { c: "🎣", k: "peche" },
      { c: "🏊", k: "natation nage piscine" },
      { c: "🚴", k: "velo cyclisme" },
      { c: "🏋️", k: "musculation halterophilie" },
      { c: "🤸", k: "gym roue acrobatie" },
      { c: "🤼", k: "lutte bagarre" },
      { c: "⛷️", k: "ski" },
      { c: "🏂", k: "snowboard" },
      { c: "🏇", k: "cheval course hippisme" },
      { c: "🎯", k: "cible dans le mille precis" },
      { c: "🎲", k: "des hasard chance" },
      { c: "🃏", k: "joker carte" },
      { c: "🎮", k: "jeu video manette" },
      { c: "♟️", k: "echecs strategie" },
    ],
  },
  {
    id: "animaux",
    label: "Animaux",
    icon: "🐶",
    emojis: [
      { c: "🐶", k: "chien toutou" },
      { c: "🐱", k: "chat minou" },
      { c: "🐭", k: "souris" },
      { c: "🐹", k: "hamster" },
      { c: "🐰", k: "lapin" },
      { c: "🦊", k: "renard" },
      { c: "🐻", k: "ours" },
      { c: "🐼", k: "panda" },
      { c: "🐨", k: "koala" },
      { c: "🐯", k: "tigre" },
      { c: "🦁", k: "lion" },
      { c: "🐮", k: "vache" },
      { c: "🐷", k: "cochon porc" },
      { c: "🐸", k: "grenouille" },
      { c: "🐵", k: "singe" },
      { c: "🐔", k: "poule poulet" },
      { c: "🐧", k: "pingouin manchot" },
      { c: "🐦", k: "oiseau" },
      { c: "🐤", k: "poussin" },
      { c: "🦆", k: "canard" },
      { c: "🦅", k: "aigle rapace" },
      { c: "🦉", k: "hibou chouette" },
      { c: "🦇", k: "chauve souris" },
      { c: "🐺", k: "loup" },
      { c: "🐗", k: "sanglier" },
      { c: "🐴", k: "cheval" },
      { c: "🦄", k: "licorne" },
      { c: "🐝", k: "abeille" },
      { c: "🐛", k: "chenille ver" },
      { c: "🦋", k: "papillon" },
      { c: "🐌", k: "escargot lent" },
      { c: "🐞", k: "coccinelle" },
      { c: "🐜", k: "fourmi" },
      { c: "🕷️", k: "araignee" },
      { c: "🦂", k: "scorpion" },
      { c: "🐢", k: "tortue lent" },
      { c: "🐍", k: "serpent" },
      { c: "🦎", k: "lezard" },
      { c: "🦖", k: "dinosaure trex" },
      { c: "🐙", k: "poulpe pieuvre" },
      { c: "🦑", k: "calamar" },
      { c: "🦐", k: "crevette" },
      { c: "🦀", k: "crabe" },
      { c: "🐟", k: "poisson" },
      { c: "🐬", k: "dauphin" },
      { c: "🐳", k: "baleine" },
      { c: "🦈", k: "requin" },
      { c: "🐊", k: "crocodile" },
      { c: "🐘", k: "elephant" },
      { c: "🦏", k: "rhinoceros" },
      { c: "🐪", k: "chameau dromadaire" },
      { c: "🦒", k: "girafe" },
      { c: "🦘", k: "kangourou" },
      { c: "🐕", k: "chien laisse" },
      { c: "🐈", k: "chat maison" },
      { c: "🐓", k: "coq gaulois france" },
      { c: "🦃", k: "dinde" },
      { c: "🕊️", k: "colombe paix" },
      { c: "🐇", k: "lapin course" },
      { c: "🐁", k: "souris blanche" },
      { c: "🌵", k: "cactus" },
      { c: "🌲", k: "sapin arbre" },
      { c: "🌴", k: "palmier vacances" },
      { c: "🍀", k: "trefle chance porte bonheur" },
      { c: "🍁", k: "erable automne" },
      { c: "🍂", k: "feuilles automne" },
      { c: "🌷", k: "tulipe fleur" },
      { c: "🌹", k: "rose fleur amour" },
      { c: "🌻", k: "tournesol fleur" },
      { c: "🌸", k: "fleur cerisier" },
      { c: "🌈", k: "arc en ciel" },
      { c: "☀️", k: "soleil beau temps" },
      { c: "⛅", k: "nuage soleil" },
      { c: "☁️", k: "nuage" },
      { c: "🌧️", k: "pluie" },
      { c: "⛈️", k: "orage" },
      { c: "❄️", k: "neige flocon froid" },
      { c: "⛄", k: "bonhomme de neige" },
      { c: "🌊", k: "vague mer" },
      { c: "🌙", k: "lune nuit" },
      { c: "🔴", k: "rond rouge" },
      { c: "🟢", k: "rond vert" },
    ],
  },
  {
    id: "nourriture",
    label: "Nourriture",
    icon: "🍔",
    emojis: [
      { c: "🍏", k: "pomme verte" },
      { c: "🍎", k: "pomme rouge" },
      { c: "🍐", k: "poire" },
      { c: "🍊", k: "orange clementine" },
      { c: "🍋", k: "citron" },
      { c: "🍌", k: "banane" },
      { c: "🍉", k: "pasteque" },
      { c: "🍇", k: "raisin" },
      { c: "🍓", k: "fraise" },
      { c: "🫐", k: "myrtille" },
      { c: "🍒", k: "cerise" },
      { c: "🍑", k: "peche fesses" },
      { c: "🥭", k: "mangue" },
      { c: "🍍", k: "ananas" },
      { c: "🥥", k: "noix de coco" },
      { c: "🥝", k: "kiwi" },
      { c: "🍅", k: "tomate" },
      { c: "🥑", k: "avocat" },
      { c: "🍆", k: "aubergine" },
      { c: "🥕", k: "carotte" },
      { c: "🌽", k: "mais epi" },
      { c: "🌶️", k: "piment epice fort" },
      { c: "🥔", k: "pomme de terre patate" },
      { c: "🧄", k: "ail" },
      { c: "🧅", k: "oignon" },
      { c: "🍞", k: "pain" },
      { c: "🥖", k: "baguette france" },
      { c: "🥐", k: "croissant petit dejeuner" },
      { c: "🧀", k: "fromage" },
      { c: "🥚", k: "oeuf" },
      { c: "🍳", k: "oeuf plat cuisine" },
      { c: "🥓", k: "bacon lard" },
      { c: "🍔", k: "burger hamburger" },
      { c: "🍟", k: "frites" },
      { c: "🌭", k: "hot dog" },
      { c: "🍕", k: "pizza" },
      { c: "🥪", k: "sandwich" },
      { c: "🌮", k: "taco" },
      { c: "🌯", k: "burrito wrap" },
      { c: "🥙", k: "kebab galette" },
      { c: "🥗", k: "salade" },
      { c: "🍝", k: "pates spaghetti" },
      { c: "🍜", k: "nouilles ramen soupe" },
      { c: "🍲", k: "plat mijote" },
      { c: "🍛", k: "curry riz" },
      { c: "🍣", k: "sushi" },
      { c: "🍤", k: "crevette frite" },
      { c: "🥘", k: "paella poele" },
      { c: "🍗", k: "cuisse poulet" },
      { c: "🥩", k: "steak viande" },
      { c: "🍖", k: "viande os" },
      { c: "🧆", k: "falafel" },
      { c: "🍿", k: "popcorn cinema" },
      { c: "🧂", k: "sel" },
      { c: "🍦", k: "glace" },
      { c: "🍩", k: "donut beignet" },
      { c: "🍪", k: "cookie biscuit" },
      { c: "🎂", k: "gateau anniversaire" },
      { c: "🍰", k: "part de gateau" },
      { c: "🧁", k: "cupcake" },
      { c: "🍫", k: "chocolat" },
      { c: "🍬", k: "bonbon" },
      { c: "🍯", k: "miel" },
      { c: "☕", k: "cafe" },
      { c: "🍵", k: "the" },
      { c: "🧃", k: "jus brique" },
      { c: "🥤", k: "soda gobelet" },
      { c: "🍺", k: "biere" },
      { c: "🍻", k: "bieres sante tchin trinque" },
      { c: "🍷", k: "vin verre" },
      { c: "🥂", k: "champagne trinque celebration" },
      { c: "🍾", k: "bouteille champagne fete" },
      { c: "🥃", k: "whisky verre" },
      { c: "🍸", k: "cocktail" },
      { c: "🧊", k: "glacon froid" },
    ],
  },
  {
    id: "lieux",
    label: "Voyage",
    icon: "🚗",
    emojis: [
      { c: "🚗", k: "voiture auto" },
      { c: "🚕", k: "taxi" },
      { c: "🚙", k: "suv voiture" },
      { c: "🚌", k: "bus car" },
      { c: "🚎", k: "trolley bus" },
      { c: "🏎️", k: "formule 1 course rapide" },
      { c: "🚓", k: "voiture police" },
      { c: "🚑", k: "ambulance" },
      { c: "🚒", k: "pompiers camion" },
      { c: "🚚", k: "camion livraison" },
      { c: "🚜", k: "tracteur" },
      { c: "🏍️", k: "moto" },
      { c: "🛵", k: "scooter" },
      { c: "🚲", k: "velo" },
      { c: "🛴", k: "trottinette" },
      { c: "🚂", k: "train locomotive" },
      { c: "🚄", k: "tgv train rapide" },
      { c: "🚇", k: "metro" },
      { c: "✈️", k: "avion voyage" },
      { c: "🛫", k: "decollage depart" },
      { c: "🛬", k: "atterrissage arrivee" },
      { c: "🚁", k: "helicoptere" },
      { c: "🚀", k: "fusee decolle rapide" },
      { c: "🛸", k: "soucoupe ovni" },
      { c: "⛵", k: "voilier bateau" },
      { c: "🚢", k: "bateau paquebot" },
      { c: "⚓", k: "ancre marine" },
      { c: "🏠", k: "maison" },
      { c: "🏡", k: "maison jardin" },
      { c: "🏢", k: "immeuble bureau" },
      { c: "🏥", k: "hopital" },
      { c: "🏦", k: "banque" },
      { c: "🏨", k: "hotel" },
      { c: "🏪", k: "magasin superette" },
      { c: "🏫", k: "ecole" },
      { c: "⛪", k: "eglise" },
      { c: "🗼", k: "tour tokyo" },
      { c: "🗽", k: "statue liberte new york" },
      { c: "🗿", k: "moai statue" },
      { c: "🎡", k: "grande roue" },
      { c: "🎢", k: "montagnes russes" },
      { c: "🏖️", k: "plage vacances" },
      { c: "🏝️", k: "ile deserte" },
      { c: "⛰️", k: "montagne" },
      { c: "🌋", k: "volcan" },
      { c: "🏕️", k: "camping tente" },
      { c: "🌃", k: "ville nuit" },
      { c: "🌆", k: "ville coucher soleil" },
      { c: "🌉", k: "pont nuit" },
      { c: "🗺️", k: "carte monde" },
      { c: "🧭", k: "boussole direction" },
      { c: "📍", k: "position lieu epingle" },
    ],
  },
  {
    id: "objets",
    label: "Objets",
    icon: "🎁",
    emojis: [
      { c: "📱", k: "telephone portable" },
      { c: "💻", k: "ordinateur portable" },
      { c: "🖥️", k: "ordinateur ecran" },
      { c: "⌨️", k: "clavier" },
      { c: "🖱️", k: "souris ordinateur" },
      { c: "🖨️", k: "imprimante" },
      { c: "📷", k: "appareil photo" },
      { c: "📸", k: "photo flash" },
      { c: "🎥", k: "camera film" },
      { c: "📺", k: "television tv" },
      { c: "📻", k: "radio" },
      { c: "🎧", k: "casque musique" },
      { c: "🎤", k: "micro chante" },
      { c: "🎵", k: "musique note" },
      { c: "🎶", k: "musique notes" },
      { c: "🎸", k: "guitare" },
      { c: "🎹", k: "piano clavier" },
      { c: "💡", k: "idee ampoule" },
      { c: "🔦", k: "lampe torche" },
      { c: "🕯️", k: "bougie" },
      { c: "🔋", k: "batterie pile" },
      { c: "🔌", k: "prise electrique" },
      { c: "💰", k: "argent sac" },
      { c: "💵", k: "billet dollar" },
      { c: "💶", k: "billet euro" },
      { c: "💳", k: "carte bancaire" },
      { c: "🧾", k: "recu facture ticket" },
      { c: "💎", k: "diamant precieux" },
      { c: "⚖️", k: "balance justice equilibre" },
      { c: "🔧", k: "cle outil repare" },
      { c: "🔨", k: "marteau" },
      { c: "🛠️", k: "outils bricolage" },
      { c: "🧰", k: "boite a outils" },
      { c: "🔑", k: "cle" },
      { c: "🔒", k: "cadenas ferme verrouille" },
      { c: "🔓", k: "cadenas ouvert" },
      { c: "🛡️", k: "bouclier defense protection" },
      { c: "🎁", k: "cadeau" },
      { c: "🎈", k: "ballon fete" },
      { c: "🎀", k: "noeud ruban" },
      { c: "🧨", k: "petard explosif" },
      { c: "✨", k: "etincelles brillant magique" },
      { c: "🎇", k: "feu artifice etincelle" },
      { c: "🎆", k: "feu artifice" },
      { c: "📅", k: "calendrier date" },
      { c: "📆", k: "calendrier jour" },
      { c: "⏰", k: "reveil alarme heure" },
      { c: "⌛", k: "sablier temps" },
      { c: "📊", k: "graphique statistiques barres" },
      { c: "📈", k: "hausse progression monte" },
      { c: "📉", k: "baisse chute descend" },
      { c: "📋", k: "presse papier liste" },
      { c: "📝", k: "note ecrit crayon" },
      { c: "✏️", k: "crayon" },
      { c: "📌", k: "punaise epingle" },
      { c: "📎", k: "trombone piece jointe" },
      { c: "📁", k: "dossier" },
      { c: "📢", k: "annonce haut parleur" },
      { c: "🔔", k: "cloche notification" },
      { c: "🔕", k: "cloche barree silence" },
      { c: "📨", k: "message courrier" },
      { c: "📮", k: "boite aux lettres" },
      { c: "🔍", k: "loupe recherche" },
      { c: "🔎", k: "loupe zoom" },
      { c: "💊", k: "medicament pilule" },
      { c: "🩹", k: "pansement" },
      { c: "🚽", k: "toilettes wc" },
      { c: "🧻", k: "papier toilette" },
      { c: "🛒", k: "caddie courses" },
      { c: "🧹", k: "balai menage" },
      { c: "🗑️", k: "poubelle jeter" },
    ],
  },
  {
    id: "symboles",
    label: "Symboles",
    icon: "❤️",
    emojis: [
      { c: "❤️", k: "coeur rouge amour" },
      { c: "🧡", k: "coeur orange" },
      { c: "💛", k: "coeur jaune" },
      { c: "💚", k: "coeur vert" },
      { c: "💙", k: "coeur bleu" },
      { c: "💜", k: "coeur violet" },
      { c: "🖤", k: "coeur noir" },
      { c: "🤍", k: "coeur blanc" },
      { c: "🤎", k: "coeur marron" },
      { c: "💔", k: "coeur brise rupture" },
      { c: "❣️", k: "coeur exclamation" },
      { c: "💕", k: "deux coeurs amour" },
      { c: "💞", k: "coeurs tournent" },
      { c: "💓", k: "coeur bat" },
      { c: "💗", k: "coeur grandit" },
      { c: "💖", k: "coeur brillant" },
      { c: "💘", k: "coeur fleche cupidon" },
      { c: "💝", k: "coeur cadeau" },
      { c: "💯", k: "cent pour cent parfait a fond" },
      { c: "✅", k: "coche valide ok fait" },
      { c: "☑️", k: "case cochee" },
      { c: "✔️", k: "coche valide" },
      { c: "❌", k: "croix faux non annule" },
      { c: "❎", k: "croix verte" },
      { c: "⭕", k: "cercle rouge" },
      { c: "❗", k: "exclamation attention" },
      { c: "❓", k: "question interrogation" },
      { c: "❕", k: "exclamation blanc" },
      { c: "❔", k: "question blanc" },
      { c: "⚠️", k: "attention danger avertissement" },
      { c: "🚫", k: "interdit stop" },
      { c: "🔞", k: "interdit mineurs" },
      { c: "♻️", k: "recyclage" },
      { c: "🆕", k: "nouveau new" },
      { c: "🆗", k: "ok" },
      { c: "🆙", k: "up haut" },
      { c: "🔝", k: "top haut" },
      { c: "🔙", k: "retour arriere" },
      { c: "🔜", k: "bientot prochainement" },
      { c: "▶️", k: "lecture play" },
      { c: "⏸️", k: "pause" },
      { c: "⏹️", k: "stop arret" },
      { c: "⏭️", k: "suivant" },
      { c: "🔀", k: "aleatoire melange" },
      { c: "🔁", k: "repeter boucle" },
      { c: "➕", k: "plus ajouter" },
      { c: "➖", k: "moins retirer" },
      { c: "✖️", k: "multiplier croix" },
      { c: "🟰", k: "egal" },
      { c: "💤", k: "dort zzz sommeil" },
      { c: "💭", k: "bulle pensee" },
      { c: "💬", k: "bulle message discussion" },
      { c: "🔇", k: "muet son coupe" },
      { c: "🔊", k: "son fort volume" },
      { c: "🏳️", k: "drapeau blanc abandon" },
      { c: "🏴", k: "drapeau noir" },
      { c: "🏁", k: "damier arrivee fin course" },
      { c: "🇫🇷", k: "france francais drapeau bleu blanc rouge" },
      { c: "🇧🇪", k: "belgique belge drapeau" },
      { c: "🇮🇹", k: "italie italien drapeau" },
      { c: "🇪🇸", k: "espagne espagnol drapeau" },
      { c: "🇩🇪", k: "allemagne allemand drapeau" },
      { c: "🇬🇧", k: "angleterre royaume uni drapeau" },
      { c: "🇵🇹", k: "portugal portugais drapeau" },
      { c: "🇳🇱", k: "pays bas hollande drapeau" },
      { c: "🇧🇷", k: "bresil bresilien drapeau" },
      { c: "🇦🇷", k: "argentine drapeau" },
      { c: "🇲🇦", k: "maroc marocain drapeau" },
      { c: "🇩🇿", k: "algerie algerien drapeau" },
      { c: "🇹🇳", k: "tunisie tunisien drapeau" },
      { c: "🇸🇳", k: "senegal drapeau" },
      { c: "🇨🇮", k: "cote ivoire drapeau" },
      { c: "🇺🇸", k: "etats unis americain drapeau" },
      { c: "🇨🇭", k: "suisse drapeau" },
      { c: "🇵🇱", k: "pologne polonais drapeau" },
      { c: "🇹🇷", k: "turquie turc drapeau" },
      { c: "🇯🇵", k: "japon japonais drapeau" },
    ],
  },
];

/**
 * Met un texte à plat pour la recherche : minuscules, sans accent.
 * « Bière » et « biere » doivent tomber sur la même entrée — sinon la
 * recherche ne marche que pour ceux qui tapent les accents.
 */
export function normaliserRecherche(texte: string): string {
  return texte
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .trim();
}

/** Toutes les émoticônes, tous onglets confondus. */
export const TOUS_LES_EMOJIS: EmojiEntry[] = EMOJI_CATEGORIES.flatMap((categorie) => categorie.emojis);

/**
 * Recherche par mot-clé français. Renvoie une liste vide si la requête est
 * vide : l'appelant affiche alors les catégories normalement.
 */
export function chercherEmojis(requete: string): EmojiEntry[] {
  const terme = normaliserRecherche(requete);
  if (!terme) return [];
  return TOUS_LES_EMOJIS.filter((entree) => entree.k.includes(terme));
}
