/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ClassementRouteImport } from './routes/classement'
import { Route as GazetteRouteImport } from './routes/gazette'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as PronosticsRouteImport } from './routes/pronostics'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as TropheesRouteImport } from './routes/trophees'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassementRoute = ClassementRouteImport.update({
  id: '/classement',
  path: '/classement',
  getParentRoute: () => rootRouteImport,
} as any)
const GazetteRoute = GazetteRouteImport.update({
  id: '/gazette',
  path: '/gazette',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const PronosticsRoute = PronosticsRouteImport.update({
  id: '/pronostics',
  path: '/pronostics',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const TropheesRoute = TropheesRouteImport.update({
  id: '/trophees',
  path: '/trophees',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/classement': typeof ClassementRoute
  '/gazette': typeof GazetteRoute
  '/profil': typeof ProfilRoute
  '/pronostics': typeof PronosticsRoute
  '/stats': typeof StatsRoute
  '/trophees': typeof TropheesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/classement': typeof ClassementRoute
  '/gazette': typeof GazetteRoute
  '/profil': typeof ProfilRoute
  '/pronostics': typeof PronosticsRoute
  '/stats': typeof StatsRoute
  '/trophees': typeof TropheesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/classement': typeof ClassementRoute
  '/gazette': typeof GazetteRoute
  '/profil': typeof ProfilRoute
  '/pronostics': typeof PronosticsRoute
  '/stats': typeof StatsRoute
  '/trophees': typeof TropheesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/classement'
    | '/gazette'
    | '/profil'
    | '/pronostics'
    | '/stats'
    | '/trophees'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/classement'
    | '/gazette'
    | '/profil'
    | '/pronostics'
    | '/stats'
    | '/trophees'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/classement'
    | '/gazette'
    | '/profil'
    | '/pronostics'
    | '/stats'
    | '/trophees'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ClassementRoute: typeof ClassementRoute
  GazetteRoute: typeof GazetteRoute
  ProfilRoute: typeof ProfilRoute
  PronosticsRoute: typeof PronosticsRoute
  StatsRoute: typeof StatsRoute
  TropheesRoute: typeof TropheesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classement': {
      id: '/classement'
      path: '/classement'
      fullPath: '/classement'
      preLoaderRoute: typeof ClassementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gazette': {
      id: '/gazette'
      path: '/gazette'
      fullPath: '/gazette'
      preLoaderRoute: typeof GazetteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pronostics': {
      id: '/pronostics'
      path: '/pronostics'
      fullPath: '/pronostics'
      preLoaderRoute: typeof PronosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trophees': {
      id: '/trophees'
      path: '/trophees'
      fullPath: '/trophees'
      preLoaderRoute: typeof TropheesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ClassementRoute: ClassementRoute,
  GazetteRoute: GazetteRoute,
  ProfilRoute: ProfilRoute,
  PronosticsRoute: PronosticsRoute,
  StatsRoute: StatsRoute,
  TropheesRoute: TropheesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
