/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClassementRouteImport } from './routes/classement'
import { Route as GazetteRouteImport } from './routes/gazette'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as PronosticsRouteImport } from './routes/pronostics'
import { Route as StatistiquesRouteImport } from './routes/statistiques'
import { Route as TropheesRouteImport } from './routes/trophees'
import { Route as VestiaireRouteImport } from './routes/vestiaire'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassementRoute = ClassementRouteImport.update({
  id: '/classement',
  path: '/classement',
  getParentRoute: () => rootRouteImport,
} as any)
const GazetteRoute = GazetteRouteImport.update({
  id: '/gazette',
  path: '/gazette',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const PronosticsRoute = PronosticsRouteImport.update({
  id: '/pronostics',
  path: '/pronostics',
  getParentRoute: () => rootRouteImport,
} as any)
const StatistiquesRoute = StatistiquesRouteImport.update({
  id: '/statistiques',
  path: '/statistiques',
  getParentRoute: () => rootRouteImport,
} as any)
const TropheesRoute = TropheesRouteImport.update({
  id: '/trophees',
  path: '/trophees',
  getParentRoute: () => rootRouteImport,
} as any)
const VestiaireRoute = VestiaireRouteImport.update({
  id: '/vestiaire',
  path: '/vestiaire',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/classement': typeof ClassementRoute
  '/gazette': typeof GazetteRoute
  '/profil': typeof ProfilRoute
  '/pronostics': typeof PronosticsRoute
  '/statistiques': typeof StatistiquesRoute
  '/trophees': typeof TropheesRoute
  '/vestiaire': typeof VestiaireRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/classement': typeof ClassementRoute
  '/gazette': typeof GazetteRoute
  '/profil': typeof ProfilRoute
  '/pronostics': typeof PronosticsRoute
  '/statistiques': typeof StatistiquesRoute
  '/trophees': typeof TropheesRoute
  '/vestiaire': typeof VestiaireRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/classement': typeof ClassementRoute
  '/gazette': typeof GazetteRoute
  '/profil': typeof ProfilRoute
  '/pronostics': typeof PronosticsRoute
  '/statistiques': typeof StatistiquesRoute
  '/trophees': typeof TropheesRoute
  '/vestiaire': typeof VestiaireRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/classement'
    | '/gazette'
    | '/profil'
    | '/pronostics'
    | '/statistiques'
    | '/trophees'
    | '/vestiaire'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/classement'
    | '/gazette'
    | '/profil'
    | '/pronostics'
    | '/statistiques'
    | '/trophees'
    | '/vestiaire'
  id:
    | '__root__'
    | '/'
    | '/classement'
    | '/gazette'
    | '/profil'
    | '/pronostics'
    | '/statistiques'
    | '/trophees'
    | '/vestiaire'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClassementRoute: typeof ClassementRoute
  GazetteRoute: typeof GazetteRoute
  ProfilRoute: typeof ProfilRoute
  PronosticsRoute: typeof PronosticsRoute
  StatistiquesRoute: typeof StatistiquesRoute
  TropheesRoute: typeof TropheesRoute
  VestiaireRoute: typeof VestiaireRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classement': {
      id: '/classement'
      path: '/classement'
      fullPath: '/classement'
      preLoaderRoute: typeof ClassementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gazette': {
      id: '/gazette'
      path: '/gazette'
      fullPath: '/gazette'
      preLoaderRoute: typeof GazetteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pronostics': {
      id: '/pronostics'
      path: '/pronostics'
      fullPath: '/pronostics'
      preLoaderRoute: typeof PronosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistiques': {
      id: '/statistiques'
      path: '/statistiques'
      fullPath: '/statistiques'
      preLoaderRoute: typeof StatistiquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trophees': {
      id: '/trophees'
      path: '/trophees'
      fullPath: '/trophees'
      preLoaderRoute: typeof TropheesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vestiaire': {
      id: '/vestiaire'
      path: '/vestiaire'
      fullPath: '/vestiaire'
      preLoaderRoute: typeof VestiaireRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClassementRoute: ClassementRoute,
  GazetteRoute: GazetteRoute,
  ProfilRoute: ProfilRoute,
  PronosticsRoute: PronosticsRoute,
  StatistiquesRoute: StatistiquesRoute,
  TropheesRoute: TropheesRoute,
  VestiaireRoute: VestiaireRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
